---

- hosts: all
  become: true
  tasks:


  - name: install apache2 and php package and update cache
    package:
      name: 
       - httpd 
       - php 
      update_cache: yes
      state: latest 

