---

- hosts: all
  become: true
  tasks:

  - name: install updates
    yum:
     update_only: yes
     update_cache: yes
   

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php package and update cache
    yum:
      name: 
       - httpd 
       - php 
      state: latest

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644 

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb
    yum:
      name: mariadb
      state: latest
